sudo: required

env:
  matrix:
    - EMACS_VERSION=emacs-23.4-bin EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-23.4-bin EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-23.4-travis EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-23.4-travis EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.1-bin EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.1-bin EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.1-travis EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.1-travis EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.2-bin EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.2-bin EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.2-travis EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.2-travis EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.3-bin EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.3-bin EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.3-travis EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.3-travis EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.4-bin EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.4-bin EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.4-travis EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.4-travis EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.5-bin EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.5-bin EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-24.5-travis EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-24.5-travis EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-25.1-travis EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-25.1-travis EVM_CONFIG_PATH=no
    - EMACS_VERSION=emacs-25.2-travis EVM_CONFIG_PATH=yes
    - EMACS_VERSION=emacs-25.2-travis EVM_CONFIG_PATH=no

before_install:
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - export PATH="/home/travis/.evm/bin:$PATH"
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - if [ "$EVM_CONFIG_PATH" = yes ]; then evm config path /tmp; fi
  - evm install "$EMACS_VERSION" --use

script:
  - emacs -Q --batch --eval '(message (emacs-version))'
