language: emacs-lisp
sudo: required
env:
  matrix:
    - EMACS_VERSION=emacs-24.3-bin
    - EMACS_VERSION=emacs-24.4-bin
    - EMACS_VERSION=emacs-24.5-bin
    - EMACS_VERSION=emacs-25.1-bin
    - EMACS_VERSION=emacs-snapshot

before_install:
  - |
    # Use the Ubuntu Emacs team's regularly updated snapshot packages.
    if [ "$EMACS_VERSION" = emacs-snapshot ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot-nox &&
        sudo update-alternatives --set emacs $(which emacs-snapshot)
    # Use Emacs Version Manager for all other versions.
    else
        sudo mkdir /usr/local/evm &&
        sudo chown travis:travis /usr/local/evm &&
        export PATH="/home/travis/.evm/bin:$PATH" &&
        curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash &&
        { evm install $EMACS_VERSION --use || true; }
    fi

script:
  # Make sure the exact emacs version can be found in the build output.
  - emacs -Q --batch --eval '(message (emacs-version))'
  - make test
